site_name: The Internals of Spark on Kubernetes
site_url: https://jaceklaskowski.github.io/spark-kubernetes-book
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Spark on Kubernetes

repo_name: spark-kubernetes-book
repo_url: https://github.com/jaceklaskowski/spark-kubernetes-book
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Spark on Kubernetes
    spark_core: https://books.japila.pl/apache-spark-internals
  hadoop:
    version: 3.3.1
    docs: https://hadoop.apache.org/docs/r3.3.1
    api: https://hadoop.apache.org/docs/r3.3.1/api
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api
  k8s:
    version: 5.4.1
    api: https://www.javadoc.io/doc/io.fabric8/kubernetes-client/5.4.1
    doc: https://kubernetes.io/docs
  minikube:
    docs: https://minikube.sigs.k8s.io/docs
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
  spark:
    version: 3.2.0
    github: https://github.com/apache/spark/tree/v3.2.0
    doc: http://spark.apache.org/docs/3.2.0

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - Configuration Properties: configuration-properties.md
    - KubernetesClusterManager: KubernetesClusterManager.md
    - KubernetesClusterSchedulerBackend: KubernetesClusterSchedulerBackend.md
    - KubernetesDriverEndpoint: KubernetesDriverEndpoint.md
    - Cluster Deploy Mode:
      - KubernetesClientApplication: KubernetesClientApplication.md
      - Client: Client.md
      - KubernetesDriverBuilder: KubernetesDriverBuilder.md
      - LoggingPodStatusWatcherImpl: LoggingPodStatusWatcherImpl.md
    - ExecutorPodsLifecycleManager: ExecutorPodsLifecycleManager.md
    - ExecutorPodsSnapshotsStore: ExecutorPodsSnapshotsStore.md
    - ExecutorPodsSnapshot: ExecutorPodsSnapshot.md
    - Executor Pods Watchers:
      - ExecutorPodsWatchSnapshotSource: ExecutorPodsWatchSnapshotSource.md
      - ExecutorPodsWatcher: ExecutorPodsWatcher.md
    - ExecutorPodsPollingSnapshotSource: ExecutorPodsPollingSnapshotSource.md
    - ExecutorPodsSnapshotsStoreImpl: ExecutorPodsSnapshotsStoreImpl.md
    - SnapshotsSubscriber: SnapshotsSubscriber.md
    - ExecutorPodsAllocator: ExecutorPodsAllocator.md
    - KubernetesExecutorBuilder: KubernetesExecutorBuilder.md
    - LoggingPodStatusWatcher: LoggingPodStatusWatcher.md
    - PollRunnable: PollRunnable.md
    - ClientArguments: ClientArguments.md
    - Configuration Metadata:
      - KubernetesConf: KubernetesConf.md
      - KubernetesDriverConf: KubernetesDriverConf.md
      - KubernetesExecutorConf: KubernetesExecutorConf.md
    - Kubernetes Pod Feature Steps:
      - KubernetesFeatureConfigStep: KubernetesFeatureConfigStep.md
      - BasicDriverFeatureStep: BasicDriverFeatureStep.md
      - BasicExecutorFeatureStep: BasicExecutorFeatureStep.md
      - DriverCommandFeatureStep: DriverCommandFeatureStep.md
      - DriverKubernetesCredentialsFeatureStep: DriverKubernetesCredentialsFeatureStep.md
      - DriverServiceFeatureStep: DriverServiceFeatureStep.md
      - EnvSecretsFeatureStep: EnvSecretsFeatureStep.md
      - ExecutorKubernetesCredentialsFeatureStep: ExecutorKubernetesCredentialsFeatureStep.md
      - LocalDirsFeatureStep: LocalDirsFeatureStep.md
      - MountSecretsFeatureStep: MountSecretsFeatureStep.md
      - MountVolumesFeatureStep: MountVolumesFeatureStep.md
      - PodTemplateConfigMapStep: PodTemplateConfigMapStep.md
    - K8SSparkSubmitOperation: K8SSparkSubmitOperation.md
    - KubernetesVolumeSpec: KubernetesVolumeSpec.md
    - Utilities:
      - KubernetesUtils: KubernetesUtils.md
      - KubernetesClientUtils: KubernetesClientUtils.md
      - KubernetesVolumeUtils: KubernetesVolumeUtils.md
      - SparkKubernetesClientFactory: SparkKubernetesClientFactory.md
    - Logging: spark-logging.md
  - Features:
    - Volumes: volumes.md
  - Demos:
    - Welcome: demo/index.md
    - minikube:
      - spark-shell on minikube: demo/spark-shell-on-minikube.md
      - Running Spark Application on minikube: demo/running-spark-application-on-minikube.md
      - Spark and Local Filesystem in minikube: demo/spark-and-local-filesystem-in-minikube.md
      - PersistentVolumeClaims: demo/persistentvolumeclaims.md
      - Running Spark Examples on minikube: demo/running-spark-examples-on-minikube.md
      - Running Spark Structured Streaming on minikube: demo/running-spark-structured-streaming-on-minikube.md
    - Google Kubernetes Engine:
      - Running Spark Examples on Google Kubernetes Engine: demo/running-spark-examples-on-google-kubernetes-engine.md
      - Deploying Spark Application to Google Kubernetes Engine: demo/deploying-spark-application-to-google-kubernetes-engine.md
      - Using Cloud Storage for Checkpoint Location in Spark Structured Streaming on Google Kubernetes Engine: demo/using-cloud-storage-for-checkpoint-location-in-spark-structured-streaming-on-google-kubernetes-engine.md
